DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'db_rw') THEN
    GRANT USAGE ON SCHEMA public TO db_rw;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO db_rw;
    ALTER DEFAULT PRIVILEGES FOR ROLE db_migrator IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_rw;
  END IF;
END
$$;
